APPEARANCE_MODE = "Dark"
COLOR_THEME = "blue"
WINDOW_TITLE = "Financial Analytics Dashboard"
WINDOW_GEOMETRY = "1200x680"
DEBOUNCE_RESIZE_MS = 120

COLUMN_WEIGHT_MAIN_0 = 4
COLUMN_WEIGHT_MAIN_1 = 2
COLUMN_WEIGHT_MAIN_2 = 2
ROW_WEIGHT_MAIN_0 = 1
ROW_WEIGHT_MAIN_1 = 1

PADDING_MAIN_X = 10
PADDING_MAIN_Y = 10

CHART_PANEL_WIDTH = 600
CHART_PANEL_HEIGHT = 420
PADDING_CHART_PANEL_X = 4
PADDING_CHART_PANEL_Y = 4
PADDING_CHART_INNER_X = 6
PADDING_CHART_INNER_Y = 4

FEAR_PANEL_WIDTH = 300
FEAR_PANEL_HEIGHT = 155
PADDING_FEAR_PANEL_X = 4
PADDING_FEAR_PANEL_Y = 5
PADDING_FEAR_INNER_X = 10
PADDING_FEAR_INNER_Y = 8

SENTIMENT_PANEL_WIDTH = 300
SENTIMENT_PANEL_HEIGHT = 205
PADDING_SENTIMENT_PANEL_X = 4
PADDING_SENTIMENT_PANEL_Y = 5
PADDING_SENTIMENT_INNER_X = 8
PADDING_SENTIMENT_INNER_Y = 5
PADDING_SENTIMENT_OUTER_Y = 5

NEWS_ROW_HEIGHT = 36
PADDING_NEWS_LIST_X = 4
PADDING_NEWS_LIST_Y = 3
PADDING_NEWS_BADGE_X = 6

ORDER_PANEL_WIDTH = 420
ORDER_PANEL_HEIGHT = 610
PADDING_ORDER_PANEL_X = 4
PADDING_ORDER_PANEL_Y = 4
PADDING_ORDER_INNER_X = 8
PADDING_ORDER_INNER_Y = 5
PADDING_ORDER_OUTER_Y = 5

LEDGER_ROW_HEIGHT = 42
LEDGER_ROW_WIDTH = 5
PADDING_LEDGER_LIST_X = 4
DETAILS_PADDING_X = 8

FONT_FAMILY = "Helvetica"
FONT_SIZE_LARGE = 20
FONT_SIZE_MEDIUM = 14
FONT_SIZE_NORMAL = 12
FONT_SIZE_SUB = 11
FONT_SIZE_BODY = 10
FONT_SIZE_SMALL = 9
FONT_SIZE_MINI = 8

FALLBACK_VIX_VALUE = 20.0
NEWS_ARTICLE_LIMIT = 5
CANVAS_DEFAULT_DPI_MIN = 80

MATPLOTLIB_FIG_W = 4.0
MATPLOTLIB_FIG_H = 2.4
MATPLOTLIB_LINEWIDTH = 1.6
MATPLOTLIB_LABELSIZE = 7
MATPLOTLIB_INTERVAL_DAYS = 6

AI_PANEL_WIDTH = 285
AI_PANEL_HEIGHT = 430
PADDING_AI_HEADER_X = 8
PADDING_AI_HEADER_Y_TOP = 8
PADDING_AI_HEADER_Y_BOTTOM = 4
PADDING_AI_CHAT_X = 8
PADDING_AI_CHAT_Y = 6
PADDING_AI_DOCK_X = 8
PADDING_AI_DOCK_Y_BOTTOM = 8
PADDING_AI_INPUT_X_RIGHT = 6
AI_SEND_BTN_WIDTH = 54
PADDING_AI_GRID_X_RIGHT = 4